added PROMPT command for showing status

diff --git a/rc/_bashrc b/rc/_bashrc
--- a/rc/_bashrc
+++ b/rc/_bashrc
@@ -1,6 +1,15 @@
 #!/bin/sh
 # .BASHRC (->.KSHRC) --RC file for (interactive) Bourne-like shells.
 #
+# Contents:
+# ps1_vcs()    --Show the current git branch, if any.
+# ps1_status() --Print the status of the previous command, if it failed.
+# set_prompt() -- Customise the user prompt.
+#
+# Remarks:
+# All this script does is to set up a fairly elaborate, colourful
+# shell prompt.  It does this with a few helper functions.
+#
 #date "+.bashrc: %c"
 umask 002
 set -o ignoreeof	# ignore <CTRL d>, use exit to terminate ksh
@@ -15,9 +24,29 @@ if [ -f /etc/bashrc ]; then
     . /etc/bashrc
 fi
 
-vcs_info()
+#
+# ps1_vcs() --Show the current git branch, if any.
+#
+ps1_vcs()
 {
     git branch 2>/dev/null | sed -ne '/^[*]/s/^[*] */:/p'
+}
+
+#
+# ps1_status() --Print the status of the previous command, if it failed.
+#
+ps1_status()
+{
+    local status=$1 mode=$2
+    local mode_fg="\033[${mode}m" mode_end="\033[m"
+
+    if [ ! "$mode" ]; then
+	mode_fg= mode_end=
+    fi
+    if [ $status != 0 ]; then
+	printf "${mode_fg}command failed, status: %d${mode_end}\n" $status
+    fi
+    true
 }
 
 #
@@ -37,7 +66,7 @@ set_prompt()
 {
     local fg= bg= window_title= mode=
     if [ "$VCS" = "git" ]; then
-	vcs_prompt="\$(vcs_info)"
+	vcs_prompt="\$(ps1_vcs)"
     fi
 
     # local/remote customisation: local=green, remote=cyan
@@ -61,15 +90,18 @@ set_prompt()
     #
     case "$TERM" in
 	xterm*|rxvt*|dtterm*|cygwin)
+	    PROMPT_COMMAND="ps1_status \$? 31"
 	    window_title='\[\e]1;\h\007\e]2;\u@\h \w\007\]'
             PS1="$window_title: [\[$mode\]\h$vcs_prompt\[\e[m\]]; "
             PS2="\[\e[36m\]: > \[\e[;m\]"
 	    ;;
 	ansi|linux|vt[0-9]*)	# colourful prompt only
+	    PROMPT_COMMAND="ps1_status \$? 31"
             PS1=": [\[$mode\]\h$vcs_prompt\[\e[m\]]; "
             PS2="\[\e[36m\]: > \[\e[;m\]"
 	    ;;
 	*)				# display hostname in prompt
+	    PROMPT_COMMAND="ps1_status \$?"
             PS1=': [\h$vcs_prompt]; '
 	    PS2=': > '
 	    ;;
