hardcoded ANSI status display

diff --git a/rc/_bashrc b/rc/_bashrc
--- a/rc/_bashrc
+++ b/rc/_bashrc
@@ -37,14 +37,15 @@ ps1_vcs()
 #
 ps1_status()
 {
-    local status=$1 mode=$2
-    local mode_fg="\033[${mode}m" mode_end="\033[m"
+    local status=$? reason=
 
-    if [ ! "$mode" ]; then
-	mode_fg= mode_end=
+    if [ $status -ge 128 ]; then
+	reason="caught signal: $(($status-128))"
+    elif [ $status != 0 ]; then
+	reason="exit status: $status"
     fi
     if [ $status != 0 ]; then
-	printf "${mode_fg}# command failed, status: %d${mode_end}\n" $status
+	printf "\033[1;31m# command failed. %s\033[m\n" "$reason"
     fi
 }
 
@@ -89,13 +90,13 @@ set_prompt()
     #
     case "$TERM" in
 	xterm*|rxvt*|dtterm*|cygwin)
-	    PROMPT_COMMAND="ps1_status \$? '1;31'"
+	    PROMPT_COMMAND="ps1_status"
 	    window_title='\[\e]1;\h\007\e]2;\u@\h \w\007\]'
             PS1="$window_title: [\[$mode\]\h$vcs_prompt\[\e[m\]]; "
             PS2="\[\e[36m\]: > \[\e[;m\]"
 	    ;;
 	ansi|linux|vt[0-9]*)	# colourful prompt only
-	    PROMPT_COMMAND="ps1_status \$? '1;31'"
+	    PROMPT_COMMAND="ps1_status"
             PS1=": [\[$mode\]\h$vcs_prompt\[\e[m\]]; "
             PS2="\[\e[36m\]: > \[\e[;m\]"
 	    ;;
